// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSHQWRiSOrQvP6kcDIxq8xxnQtco9qAsE',
    appId: '1:709350303201:web:b4d5ab3d06bc9cdcac9ea0',
    messagingSenderId: '709350303201',
    projectId: 'my-app-1163d',
    authDomain: 'my-app-1163d.firebaseapp.com',
    storageBucket: 'my-app-1163d.appspot.com',
    measurementId: 'G-HR2HX6KNDM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhv8aKRh_Cab9FiDEoncZzzNp-msBQKVI',
    appId: '1:709350303201:android:5e1a1a2043d88419ac9ea0',
    messagingSenderId: '709350303201',
    projectId: 'my-app-1163d',
    storageBucket: 'my-app-1163d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-asrpTPyjjx0dUSP1UihjUbK6alEpr7A',
    appId: '1:709350303201:ios:f3c8880ee349bdcdac9ea0',
    messagingSenderId: '709350303201',
    projectId: 'my-app-1163d',
    storageBucket: 'my-app-1163d.appspot.com',
    iosBundleId: 'com.example.educationalApp',
  );
}
